name: py3
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py36h181983e_0
  - numpy=1.19.1=py36h3b9f5b6_0
  - numpy-base=1.19.1=py36hcfb5961_0
  - scipy=1.5.2=py36h912ce22_0
  - send2trash=1.8.0=pyhd8ed1ab_0
